import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { ThemeProvider } from "next-themes";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={` antialiased`}>
        <SidebarProvider>
          <ThemeProvider attribute={"class"} defaultTheme="dark">
            {children}
          </ThemeProvider>
        </SidebarProvider>
      </body>
    </html>
  );
}
